name: "pro-portal-services"
services:
  db:
    image: "postgres"
    restart: always
    container_name: pro-portal-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "pro-portal"
      POSTGRES_PASSWORD: password
    volumes:
      - database-data:/var/lib/postgresql-data/
    ports:
      - 8010:5432

volumes:
  database-data: